# -*- coding: utf-8 -*-
"""Tabelas da Terra do Sabiá v0.4 (TITULOS-E-SKILLS.md §3). Fonte única dos números das skills,
dos títulos, das quests de lição e das quests dos anciãos. Quem gera os .tres é gen_sabia_trees.py.

Enums (scripts/shared/data/skill_def.gd):
  TargetType: SINGLE 0, GROUND_AREA 1, SELF_AREA 2, CONE 3, LINE 4, SELF 5, ALLY_OR_SELF 6
  Effect: PHYSICAL_DAMAGE 0, MAGIC_DAMAGE 1, DAMAGE_OVER_TIME 2, SHIELD 3, BUFF_DEF 4, DASH_STUN 5,
          SLOW 6, HEAL 7, HOT 8, BUFF 9, DEBUFF 10, TAUNT 11, ROOT 12, STUN 13, MULTI_HIT 14,
          KNOCKBACK 15, PULL 16, BACKSTEP 17, BLINK 18, COUNTER 19, STEALTH 20, CLEANSE 21, MP_RESTORE 22
"""

SINGLE, GROUND_AREA, SELF_AREA, CONE, LINE, SELF, ALLY_OR_SELF = range(7)
(PHYSICAL, MAGIC, DOT, SHIELD, BUFF_DEF, DASH_STUN, SLOW, HEAL, HOT, BUFF, DEBUFF, TAUNT, ROOT, STUN,
 MULTI_HIT, KNOCKBACK, PULL, BACKSTEP, BLINK, COUNTER, STEALTH, CLEANSE, MP_RESTORE) = range(23)

# ------------------------------------------------------------------ títulos
# id: (nome, descrição, arquétipo, tier, pai, ramo, required_skills, required_titles, quest_only,
#      mestre, cor, sort, outfit, cloth_colors [tecido, detalhe] (r,g,b))
TEAL = (0.30980393, 0.65882355, 0.627451)
SKY = (0.3529412, 0.5647059, 0.8784314)
PURPLE = (0.5568628, 0.4, 0.76862746)

NEW_TITLES = {
    "sabia_bow_cerrado": ("Flecha do Cerrado",
        "Arco de base: ataca de longe com flechas.",
        "bow", 1, "", "", ["bow_low_shot", "bow_double_arrow", "bow_taut_draw"], [], False,
        "master_taquari", TEAL, 40, "title_cerrado", [(0.4196, 0.4588, 0.2471), (0.8784, 0.6667, 0.1647)]),
    "sabia_bow_brejo": ("Tocaia do Brejo",
        "Emboscada: fica escondido e ataca de surpresa.",
        "bow", 2, "sabia_bow_cerrado", "a", ["bow_mud_skin"], ["sabia_bow_cerrado"], False,
        "master_taquari", SKY, 41, "title_brejo", [(0.3765, 0.2941, 0.2), (0.3137, 0.4314, 0.2353)]),
    "sabia_bow_gaviao": ("Gavião-Real",
        "Tiro certeiro: acerta de muito longe e com mais crítico.",
        "bow", 2, "sabia_bow_cerrado", "b", ["bow_still_eye"], ["sabia_bow_cerrado"], False,
        "master_taquari", SKY, 42, "title_gaviao", [(0.3373, 0.3647, 0.4078), (0.8784, 0.8392, 0.7412)]),
    "sabia_support_root": ("Raiz do Cerrado",
        "Suporte: cura e protege os amigos, como a raiz que guarda água para o cerrado.",
        "support", 1, "", "", [], ["sabia_arcane_firefly", "sabia_arcane_crystal", "sabia_bow_cerrado"], True,
        "elder_aninha", PURPLE, 50, "title_root", [(0.3843, 0.2667, 0.1647), (0.4, 0.6, 0.2667)]),
    "sabia_support_buriti": ("Seiva do Buriti",
        "Cura: cura forte e rápida para quem está caindo.",
        "support", 2, "sabia_support_root", "a", ["support_broadleaf_tea"], ["sabia_support_root"], False,
        "elder_aninha", PURPLE, 51, "title_buriti", [(0.2275, 0.4196, 0.2745), (0.7529, 0.3765, 0.1647)]),
    "sabia_support_matinta": ("Assobio da Matinta",
        "Enfraquecer: tira a força, a defesa e a cura dos inimigos.",
        "support", 2, "sabia_support_root", "b", ["support_ill_whistle"], ["sabia_support_root"], False,
        "elder_aninha", PURPLE, 52, "title_matinta", [(0.1647, 0.1569, 0.2275), (0.4196, 0.2863, 0.5412)]),
    "sabia_tank_jabuti": ("Casco de Jabuti",
        "Tanque: chama os monstros para si e aguenta os golpes pelo grupo.",
        "tank", 1, "", "", [], ["sabia_blade_machete", "sabia_blade_aroeira", "sabia_blade_jaguar"], True,
        "elder_tiao", PURPLE, 60, "title_jabuti", [(0.3137, 0.3765, 0.2353), (0.7843, 0.6588, 0.3137)]),
    "sabia_tank_anta": ("Couro de Anta",
        "Guerreiro pesado: muita defesa, pisada forte e trombada.",
        "tank", 2, "sabia_tank_jabuti", "a", ["tank_thick_hide"], ["sabia_tank_jabuti"], False,
        "elder_tiao", PURPLE, 61, "title_anta", [(0.3529, 0.3216, 0.3059), (0.5412, 0.3804, 0.2275)]),
    "sabia_tank_mapinguari": ("Fúria do Mapinguari",
        "Berserker: troca defesa por força e bate mais forte quando está ferido.",
        "tank", 2, "sabia_tank_jabuti", "b", ["tank_fury"], ["sabia_tank_jabuti"], False,
        "elder_tiao", PURPLE, 62, "title_mapinguari", [(0.2745, 0.1843, 0.1294), (0.6588, 0.1843, 0.1412)]),
}

# Títulos já existentes: só o mestre (e quest_only para a Brasa no Facão, §3.0 regra 4).
EXISTING_TITLES = {
    "sabia_blade_machete": {"master_npc": "master_brisa"},
    "sabia_blade_aroeira": {"master_npc": "master_brisa"},
    "sabia_blade_jaguar": {"master_npc": "master_brisa"},
    "sabia_arcane_firefly": {"master_npc": "master_orvalho"},
    "sabia_arcane_crystal": {"master_npc": "master_orvalho"},
    "sabia_arcane_boitata": {"master_npc": "master_orvalho"},
    "sabia_hybrid_ember": {"master_npc": "elder_ze_ferreiro", "quest_only": True},
}

# Mestre de cada árvore (quests de lição).
TREE_MASTER = {
    "sabia_blade_machete": "master_brisa", "sabia_blade_aroeira": "master_brisa",
    "sabia_blade_jaguar": "master_brisa",
    "sabia_arcane_firefly": "master_orvalho", "sabia_arcane_crystal": "master_orvalho",
    "sabia_arcane_boitata": "master_orvalho",
    "sabia_bow_cerrado": "master_taquari", "sabia_bow_brejo": "master_taquari",
    "sabia_bow_gaviao": "master_taquari",
    "sabia_hybrid_ember": "elder_ze_ferreiro",
    "sabia_support_root": "elder_aninha", "sabia_support_buriti": "elder_aninha",
    "sabia_support_matinta": "elder_aninha",
    "sabia_tank_jabuti": "elder_tiao", "sabia_tank_anta": "elder_tiao", "sabia_tank_mapinguari": "elder_tiao",
}

# ------------------------------------------------------------------ skills existentes (★): posição na árvore
# id: (árvore, ordem, título para aprender (exclusive_to_title), pré-requisitos)
EXISTING_SKILLS = {
    "blade_firm_strike": ("sabia_blade_machete", 1, "", {}),
    "blade_charge": ("sabia_blade_machete", 2, "sabia_blade_machete", {"blade_firm_strike": 3}),
    "blade_steel_spin": ("sabia_blade_machete", 3, "sabia_blade_machete", {"blade_firm_strike": 3}),
    "blade_clearing_sweep": ("sabia_blade_machete", 4, "sabia_blade_machete", {"blade_steel_spin": 3}),
    "blade_iron_stance": ("sabia_blade_aroeira", 1, "sabia_blade_machete", {}),
    "blade_horizon_cut": ("sabia_blade_jaguar", 1, "sabia_blade_machete", {}),
    "arcane_spark": ("sabia_arcane_firefly", 1, "", {}),
    "arcane_frost_burst": ("sabia_arcane_firefly", 2, "sabia_arcane_firefly", {"arcane_spark": 3}),
    "arcane_creeping_flame": ("sabia_arcane_firefly", 3, "sabia_arcane_firefly", {"arcane_spark": 3}),
    "arcane_will_o_wisp": ("sabia_arcane_firefly", 4, "sabia_arcane_firefly", {"arcane_creeping_flame": 3}),
    "arcane_barrier": ("sabia_arcane_crystal", 1, "sabia_arcane_firefly", {}),
    "arcane_star_fall": ("sabia_arcane_boitata", 1, "sabia_arcane_firefly", {}),
}
# Skills exclusivas das quests dos anciãos. As iniciais também têm lições no Porto.
TAUGHT_ELSEWHERE = {"hybrid_spark_blade", "support_bottle_brew",
                    "tank_shell_knock"}


def S(sid, name, desc, school, tree, order, learn, prereq, tt, eff, mana, cd, *, cast=0.0, rng=0.0,
      radius=0.0, cone=0.0, line_len=0.0, line_w=0.0, mult=0.0, per=0.0, dur=0.0, extra=None, melee=False,
      bow=False, vfx="", icon=""):
    return dict(id=sid, name=name, desc=desc, school=school, tree=tree, order=order, learn=learn,
                prereq=prereq, target_type=tt, effect=eff, mana=mana, cd=cd, cast=cast, range=rng,
                radius=radius, cone=cone, line_len=line_len, line_w=line_w, mult=mult, per=per, dur=dur,
                extra=extra or {}, melee=melee, bow=bow, vfx=vfx, icon=icon)


MACHETE, AROEIRA, JAGUAR = "sabia_blade_machete", "sabia_blade_aroeira", "sabia_blade_jaguar"
FIREFLY, CRYSTAL, BOITATA = "sabia_arcane_firefly", "sabia_arcane_crystal", "sabia_arcane_boitata"
CERRADO, BREJO, GAVIAO = "sabia_bow_cerrado", "sabia_bow_brejo", "sabia_bow_gaviao"
EMBER = "sabia_hybrid_ember"
ROOT_T, BURITI, MATINTA = "sabia_support_root", "sabia_support_buriti", "sabia_support_matinta"
JABUTI, ANTA, MAPINGUARI = "sabia_tank_jabuti", "sabia_tank_anta", "sabia_tank_mapinguari"

# ------------------------------------------------------------------ 68 skills novas (§3.4)
NEW_SKILLS = [
    # Facão Firme
    S("blade_sharpen", "Amolar o Facão",
      "Passa a pedra no fio: +20% de ATQ e +10% de crítico por 12 s (+2% ATQ, +1% crítico e +0,5 s por nível).",
      "blade", MACHETE, 5, MACHETE, {"blade_charge": 3}, SELF, BUFF, 10, 30, dur=12,
      extra={"atk_pct": 0.2, "atk_pct_per_level": 0.02, "crit": 0.1, "crit_per_level": 0.01,
             "duration_per_level": 0.5}, melee=True, vfx="buff", icon="AF"),
    # Tronco de Aroeira
    S("blade_aroeira_reply", "Resposta da Aroeira",
      "Por 1,5 s, anula o próximo golpe corpo a corpo de um monstro e devolve 200% do ATQ (+15% e +0,1 s por nível).",
      "blade", AROEIRA, 2, AROEIRA, {"blade_iron_stance": 3}, SELF, COUNTER, 20, 18, dur=1.5,
      extra={"reflect_mult": 2.0, "reflect_mult_per_level": 0.15, "duration_per_level": 0.1},
      melee=True, vfx="counter", icon="RA"),
    S("blade_root_grip", "Raiz Presa",
      "Crava o pé no chão: prende os inimigos em volta (2,5 células) por 2 s (+0,1 s por nível).",
      "blade", AROEIRA, 3, AROEIRA, {"blade_iron_stance": 3}, SELF_AREA, ROOT, 16, 14, radius=2.5, dur=2.0,
      extra={"duration_per_level": 0.1}, vfx="root", icon="RP"),
    S("blade_thick_bark", "Casca Grossa",
      "Recebe 30% menos dano por 6 s (−2% e +0,3 s por nível).",
      "blade", AROEIRA, 4, AROEIRA, {"blade_aroeira_reply": 3}, SELF, BUFF, 14, 20, dur=6,
      extra={"dmg_taken_pct": -0.3, "dmg_taken_pct_per_level": -0.02, "duration_per_level": 0.3},
      vfx="guard", icon="CG"),
    S("blade_trunk_call", "Chamado do Tronco",
      "Provoca: os monstros em volta (4 células) atacam você por 4 s (+0,2 s por nível).",
      "blade", AROEIRA, 5, AROEIRA, {"blade_root_grip": 3}, SELF_AREA, TAUNT, 12, 16, radius=4, dur=4,
      extra={"duration_per_level": 0.2}, vfx="taunt", icon="CT"),
    # Garra da Onça
    S("blade_jaguar_leap", "Bote da Onça",
      "Salta até o alvo (6 células) e causa 160% do ATQ com +30% de chance de crítico (+12% por nível).",
      "blade", JAGUAR, 2, JAGUAR, {"blade_horizon_cut": 3}, SINGLE, PHYSICAL, 24, 14, rng=6, mult=1.6, per=0.12,
      extra={"dash": 1, "crit_bonus": 0.3}, melee=True, vfx="dash", icon="BO"),
    S("blade_claw_rake", "Unhada",
      "Três golpes rápidos de 70% do ATQ cada (+6% por nível).",
      "blade", JAGUAR, 3, JAGUAR, {"blade_jaguar_leap": 1}, SINGLE, MULTI_HIT, 14, 7, rng=1.5, mult=0.7, per=0.06,
      extra={"hits": 3}, melee=True, vfx="slash", icon="UN"),
    S("blade_blood_scent", "Faro de Sangue",
      "+25% de chance de crítico por 8 s (+1,5% e +0,4 s por nível).",
      "blade", JAGUAR, 4, JAGUAR, {"blade_claw_rake": 3}, SELF, BUFF, 12, 25, dur=8,
      extra={"crit": 0.25, "crit_per_level": 0.015, "duration_per_level": 0.4}, vfx="buff", icon="FS"),
    S("blade_jaguar_roar", "Rugido da Onça",
      "Ruge num cone de 90° (3 células): inimigos com −20% de ATQ por 6 s (−1,5% e +0,3 s por nível).",
      "blade", JAGUAR, 5, JAGUAR, {"blade_jaguar_leap": 3}, CONE, DEBUFF, 16, 18, radius=3, cone=90, dur=6,
      extra={"atk_pct": -0.2, "atk_pct_per_level": -0.015, "duration_per_level": 0.3}, vfx="debuff", icon="RO"),
    # Luz de Vaga-lume
    S("arcane_firefly_swarm", "Enxame de Vaga-lumes",
      "Quatro luzes vão no alvo, cada uma com 40% do MATQ (+4% por nível).",
      "arcane", FIREFLY, 5, FIREFLY, {"arcane_will_o_wisp": 3}, SINGLE, MULTI_HIT, 20, 10, rng=8, mult=0.4, per=0.04,
      extra={"hits": 4, "damage_kind": "magic"}, vfx="spark", icon="EV"),
    # Guarda do Cristal
    S("arcane_shared_crystal", "Cristal Repartido",
      "Até 3 aliados a 6 células ganham um escudo de 30 + MATQ × 0,8 por 6 s (+10% por nível).",
      "arcane", CRYSTAL, 2, CRYSTAL, {"arcane_barrier": 3}, SELF_AREA, SHIELD, 34, 30, radius=6, dur=6,
      extra={"shield_base": 30, "shield_matk_ratio": 0.8, "shield_per_level": 0.1, "max_targets": 3},
      vfx="shield", icon="CR"),
    S("arcane_crystal_prison", "Prisão de Cristal",
      "Fecha o alvo num cristal: atordoa por 2,5 s (+0,1 s por nível).",
      "arcane", CRYSTAL, 3, CRYSTAL, {"arcane_barrier": 3}, SINGLE, STUN, 22, 16, rng=8, dur=2.5,
      extra={"duration_per_level": 0.1}, vfx="stun", icon="PC"),
    S("arcane_crystal_wall", "Muralha de Cristal",
      "Aliados a 3 células recebem 25% menos dano por 6 s (−1,5% e +0,3 s por nível).",
      "arcane", CRYSTAL, 4, CRYSTAL, {"arcane_shared_crystal": 3}, SELF_AREA, BUFF, 26, 24, radius=3, dur=6,
      extra={"dmg_taken_pct": -0.25, "dmg_taken_pct_per_level": -0.015, "duration_per_level": 0.3},
      vfx="shield", icon="MC"),
    S("arcane_crystal_glow", "Brilho do Cristal",
      "Aliados a 6 células recuperam 15% da mana máxima em 8 s (+1% por nível).",
      "arcane", CRYSTAL, 5, CRYSTAL, {"arcane_crystal_prison": 3}, SELF_AREA, MP_RESTORE, 10, 40, radius=6, dur=8,
      extra={"mp_pct": 0.15, "mp_pct_per_level": 0.01}, vfx="mana", icon="BC"),
    # Olho do Boitatá
    S("arcane_star_step", "Passo Estelar",
      "Some e aparece numa célula livre a até 5 células.",
      "arcane", BOITATA, 2, BOITATA, {"arcane_star_fall": 3}, GROUND_AREA, BLINK, 24, 16, rng=5, radius=0.5,
      vfx="blink", icon="PE"),
    S("arcane_fire_gaze", "Olhar de Fogo",
      "Um raio em linha (12 células) com 200% do MATQ (+15% por nível).",
      "arcane", BOITATA, 3, BOITATA, {"arcane_star_fall": 3}, LINE, MAGIC, 28, 12, rng=12, line_len=12, line_w=1,
      mult=2.0, per=0.15, vfx="flame", icon="OF"),
    S("arcane_fire_serpent", "Serpente de Fogo",
      "Deixa um rastro em linha (8 células) que queima por 5 s: 45% do MATQ por segundo (+4% por nível).",
      "arcane", BOITATA, 4, BOITATA, {"arcane_fire_gaze": 3}, LINE, DOT, 30, 18, rng=8, line_len=8, line_w=1.5,
      mult=0.45, per=0.04, dur=5, vfx="flame", icon="SF"),
    S("arcane_ember_eyes", "Olhos em Brasa",
      "+25% de MATQ por 10 s (+2% e +0,5 s por nível).",
      "arcane", BOITATA, 5, BOITATA, {"arcane_star_step": 3}, SELF, BUFF, 16, 30, dur=10,
      extra={"matk_pct": 0.25, "matk_pct_per_level": 0.02, "duration_per_level": 0.5}, vfx="buff", icon="OB"),
    # Flecha do Cerrado (precisa de arco)
    S("bow_low_shot", "Tiro Rasante",
      "Flecha rente ao chão: 130% do ATQ a até 10 células (+10% por nível). Precisa de arco.",
      "bow", CERRADO, 1, "", {}, SINGLE, PHYSICAL, 6, 4, rng=10, mult=1.3, per=0.1, bow=True, vfx="arrow", icon="TR"),
    S("bow_double_arrow", "Flecha Dupla",
      "Duas flechas seguidas de 75% do ATQ cada (+6% por nível). Precisa de arco.",
      "bow", CERRADO, 2, "", {"bow_low_shot": 3}, SINGLE, MULTI_HIT, 12, 8, rng=10, mult=0.75, per=0.06,
      extra={"hits": 2}, bow=True, vfx="arrow", icon="FD"),
    S("bow_taut_draw", "Arco Tenso",
      "Puxa a corda até o fim (1 s): 250% do ATQ a até 12 células (+18% por nível). Precisa de arco.",
      "bow", CERRADO, 3, "", {"bow_low_shot": 3}, SINGLE, PHYSICAL, 16, 10, cast=1.0, rng=12, mult=2.5, per=0.18,
      bow=True, vfx="arrow", icon="AT"),
    S("bow_warning_arrow", "Flecha de Aviso",
      "Marca o alvo: ele recebe 10% mais dano de todos por 6 s (+1% e +0,3 s por nível). Precisa de arco.",
      "bow", CERRADO, 4, CERRADO, {"bow_double_arrow": 3}, SINGLE, DEBUFF, 14, 16, rng=10, dur=6,
      extra={"dmg_taken_pct": 0.1, "dmg_taken_pct_per_level": 0.01, "duration_per_level": 0.3},
      bow=True, vfx="debuff", icon="FA"),
    S("bow_arrow_flock", "Revoada de Flechas",
      "Chuva de flechas numa área (3 células): 120% do ATQ (+10% por nível). Precisa de arco.",
      "bow", CERRADO, 5, CERRADO, {"bow_taut_draw": 3}, GROUND_AREA, PHYSICAL, 24, 16, rng=10, radius=3,
      mult=1.2, per=0.1, bow=True, vfx="arrow", icon="RF"),
    # Tocaia do Brejo
    S("bow_mud_skin", "Pele de Barro",
      "+30% de esquiva por 8 s (+2% e +0,4 s por nível). Precisa de arco.",
      "bow", BREJO, 1, CERRADO, {}, SELF, BUFF, 12, 20, dur=8,
      extra={"evade": 0.3, "evade_per_level": 0.02, "duration_per_level": 0.4}, bow=True, vfx="buff", icon="PB"),
    S("bow_mud_hide", "Lama no Corpo",
      "Invisível para os monstros até atacar, ou por 10 s (+0,5 s por nível). Precisa de arco.",
      "bow", BREJO, 2, BREJO, {"bow_mud_skin": 3}, SELF, STEALTH, 18, 25, dur=10,
      extra={"duration_per_level": 0.5}, bow=True, vfx="stealth", icon="LC"),
    S("bow_ambush_shot", "Tocaia",
      "200% do ATQ (+100% se estiver invisível) e prende o alvo por 1,5 s (+15% por nível). Precisa de arco.",
      "bow", BREJO, 3, BREJO, {"bow_mud_hide": 1}, SINGLE, PHYSICAL, 20, 14, rng=10, mult=2.0, per=0.15,
      extra={"stealth_bonus": 1.0, "root_sec": 1.5}, bow=True, vfx="arrow", icon="TO"),
    S("bow_vine_snare", "Armadilha de Cipó",
      "Cipós prendem quem estiver na área (2 células) por 2,5 s (+0,1 s por nível). Precisa de arco.",
      "bow", BREJO, 4, BREJO, {"bow_mud_skin": 3}, GROUND_AREA, ROOT, 16, 18, rng=10, radius=2, dur=2.5,
      extra={"duration_per_level": 0.1}, bow=True, vfx="root", icon="AC"),
    S("bow_thorn_arrow", "Flecha de Espinho",
      "Veneno por 6 s: 60% do ATQ por segundo (+5% por nível). Precisa de arco.",
      "bow", BREJO, 5, BREJO, {"bow_ambush_shot": 3}, SINGLE, DOT, 14, 12, rng=10, mult=0.6, per=0.05, dur=6,
      extra={"damage_kind": "physical"}, bow=True, vfx="poison", icon="FE"),
    # Gavião-Real
    S("bow_still_eye", "Olho Parado",
      "+20% de crítico e +2 células de alcance do arco por 10 s (+1% e +0,5 s por nível). Precisa de arco.",
      "bow", GAVIAO, 1, CERRADO, {}, SELF, BUFF, 12, 25, dur=10,
      extra={"crit": 0.2, "crit_per_level": 0.01, "range_cells": 2, "duration_per_level": 0.5},
      bow=True, vfx="buff", icon="OP"),
    S("bow_true_arrow", "Flecha Sem Desvio",
      "180% do ATQ a até 14 células, ignorando 40% da DEF (+12% e +2% por nível). Precisa de arco.",
      "bow", GAVIAO, 2, GAVIAO, {"bow_still_eye": 3}, SINGLE, PHYSICAL, 20, 10, rng=14, mult=1.8, per=0.12,
      extra={"def_ignore": 0.4, "def_ignore_per_level": 0.02}, bow=True, vfx="arrow", icon="SD"),
    S("bow_sure_aim", "Mira Certeira",
      "Os próximos 3 ataques físicos são críticos (dura até 15 s, +0,5 s por nível). Precisa de arco.",
      "bow", GAVIAO, 3, GAVIAO, {"bow_still_eye": 3}, SELF, BUFF, 16, 30, dur=15,
      extra={"crit_charges": 3, "duration_per_level": 0.5}, bow=True, vfx="buff", icon="MI"),
    S("bow_hawk_dive", "Mergulho do Gavião",
      "Flecha que cai do alto: 180% do ATQ e atordoa por 1 s (+12% e +0,05 s por nível). Precisa de arco.",
      "bow", GAVIAO, 4, GAVIAO, {"bow_true_arrow": 3}, SINGLE, PHYSICAL, 22, 16, rng=12, mult=1.8, per=0.12,
      extra={"stun_sec": 1.0, "stun_per_level": 0.05}, bow=True, vfx="arrow", icon="MG"),
    S("bow_short_flight", "Voo Curto",
      "Salta 4 células para trás, para longe do alvo. Precisa de arco.",
      "bow", GAVIAO, 5, GAVIAO, {"bow_sure_aim": 1}, SELF, BACKSTEP, 14, 14,
      extra={"distance_cells": 4}, bow=True, vfx="dash", icon="VC"),
    # Brasa no Facão (Seu Zé Ferreiro)
    S("hybrid_spark_blade", "Lâmina Faiscante",
      "Por 8 s, cada ataque básico soma um golpe mágico de 20% do MATQ (+3% e +0,4 s por nível).",
      "hybrid", EMBER, 1, EMBER, {}, SELF, BUFF, 22, 30, dur=8,
      extra={"imbue_matk": 0.2, "imbue_matk_per_level": 0.03, "duration_per_level": 0.4},
      melee=True, vfx="spark", icon="LF"),
    S("hybrid_ember_cut", "Corte em Brasa",
      "150% do ATQ e queimadura por 4 s (25% do MATQ por segundo) (+10% e +2% por nível).",
      "hybrid", EMBER, 2, EMBER, {"hybrid_spark_blade": 1}, SINGLE, PHYSICAL, 18, 8, rng=1.5, mult=1.5, per=0.1,
      extra={"dot_mult": 0.25, "dot_mult_per_level": 0.02, "dot_sec": 4, "dot_kind": "magic"},
      melee=True, vfx="flame", icon="CB"),
    S("hybrid_steel_spark", "Faísca no Aço",
      "Avança até o alvo (6 células) e causa 120% do MATQ (+10% por nível).",
      "hybrid", EMBER, 3, EMBER, {"hybrid_spark_blade": 3}, SINGLE, MAGIC, 20, 12, rng=6, mult=1.2, per=0.1,
      extra={"dash": 1}, melee=True, vfx="spark", icon="FC"),
    S("hybrid_sparks", "Fagulhas",
      "Fagulhas em volta (3 células): 140% do MATQ (+10% por nível).",
      "hybrid", EMBER, 4, EMBER, {"hybrid_ember_cut": 3}, SELF_AREA, MAGIC, 22, 12, radius=3, mult=1.4, per=0.1,
      vfx="spark", icon="FG"),
    S("hybrid_ember_heart", "Coração de Brasa",
      "+10% de ATQ e de MATQ por 12 s (+1% cada e +0,5 s por nível).",
      "hybrid", EMBER, 5, EMBER, {"hybrid_steel_spark": 3}, SELF, BUFF, 18, 35, dur=12,
      extra={"atk_pct": 0.1, "atk_pct_per_level": 0.01, "matk_pct": 0.1, "matk_pct_per_level": 0.01,
             "duration_per_level": 0.5}, vfx="buff", icon="CO"),
    # Raiz do Cerrado (Vó Aninha)
    S("support_bottle_brew", "Garrafada",
      "Aliados a 4 células curam 8 + MATQ × 0,2 por segundo por 10 s (+8% por nível).",
      "support", ROOT_T, 1, ROOT_T, {}, SELF_AREA, HOT, 26, 20, radius=4, dur=10,
      extra={"hot_base": 8, "hot_matk_ratio": 0.2, "hot_per_level": 0.08}, vfx="heal", icon="GA"),
    S("support_herb_tea", "Chá de Erva",
      "Cura um aliado (8 células) em 40 + MATQ × 1,6 (+10% por nível).",
      "support", ROOT_T, 2, ROOT_T, {"support_bottle_brew": 1}, ALLY_OR_SELF, HEAL, 18, 6, rng=8,
      extra={"heal_base": 40, "heal_matk_ratio": 1.6, "heal_per_level": 0.1}, vfx="heal", icon="CE"),
    S("support_poultice", "Emplastro",
      "Tira os efeitos negativos de um aliado e cura 20 + MATQ × 0,6 (+10% por nível).",
      "support", ROOT_T, 3, ROOT_T, {"support_herb_tea": 3}, ALLY_OR_SELF, CLEANSE, 14, 12, rng=8,
      extra={"heal_base": 20, "heal_matk_ratio": 0.6, "heal_per_level": 0.1}, vfx="cleanse", icon="EM"),
    S("support_pequi_shade", "Sombra de Pequizeiro",
      "Um aliado recebe 20% menos dano por 6 s (−1,5% e +0,3 s por nível).",
      "support", ROOT_T, 4, ROOT_T, {"support_herb_tea": 3}, ALLY_OR_SELF, BUFF, 16, 18, rng=8, dur=6,
      extra={"dmg_taken_pct": -0.2, "dmg_taken_pct_per_level": -0.015, "duration_per_level": 0.3},
      vfx="shield", icon="SP"),
    S("support_mutirao", "Mutirão",
      "Todo mundo junto: aliados a 6 células ganham +10% de ATQ e de MATQ por 15 s (+1% e +0,5 s por nível).",
      "support", ROOT_T, 5, ROOT_T, {"support_poultice": 3}, SELF_AREA, BUFF, 30, 45, radius=6, dur=15,
      extra={"atk_pct": 0.1, "atk_pct_per_level": 0.01, "matk_pct": 0.1, "matk_pct_per_level": 0.01,
             "duration_per_level": 0.5}, vfx="buff", icon="MU"),
    # Seiva do Buriti
    S("support_broadleaf_tea", "Chá de Folha Larga",
      "Cura grande num aliado (8 células): 80 + MATQ × 2,4, e tira o veneno (+10% por nível).",
      "support", BURITI, 1, ROOT_T, {}, ALLY_OR_SELF, HEAL, 30, 10, rng=8,
      extra={"heal_base": 80, "heal_matk_ratio": 2.4, "heal_per_level": 0.1, "cleanse_dot": 1},
      vfx="heal", icon="FL"),
    S("support_coconut_water", "Água de Coco",
      "Cura os aliados a 6 células em 40 + MATQ × 1,0 (+10% por nível).",
      "support", BURITI, 2, BURITI, {"support_broadleaf_tea": 3}, SELF_AREA, HEAL, 34, 18, radius=6,
      extra={"heal_base": 40, "heal_matk_ratio": 1.0, "heal_per_level": 0.1}, vfx="heal", icon="AQ"),
    S("support_running_sap", "Seiva que Corre",
      "Cura contínua forte num aliado: 15 + MATQ × 0,4 por segundo por 12 s (+8% por nível).",
      "support", BURITI, 3, BURITI, {"support_broadleaf_tea": 3}, ALLY_OR_SELF, HOT, 20, 12, rng=8, dur=12,
      extra={"hot_base": 15, "hot_matk_ratio": 0.4, "hot_per_level": 0.08}, vfx="heal", icon="SC"),
    S("support_holding_root", "Raiz que Segura",
      "Por 3 s o aliado não cai abaixo de 1 de vida (+0,2 s por nível).",
      "support", BURITI, 4, BURITI, {"support_coconut_water": 3}, ALLY_OR_SELF, BUFF, 28, 60, rng=8, dur=3,
      extra={"death_ward": 1, "duration_per_level": 0.2}, vfx="shield", icon="RS"),
    S("support_new_breath", "Fôlego Novo",
      "Devolve 20% da mana máxima de um aliado (+1% por nível).",
      "support", BURITI, 5, BURITI, {"support_running_sap": 3}, ALLY_OR_SELF, MP_RESTORE, 10, 40, rng=8,
      extra={"mp_pct": 0.2, "mp_pct_per_level": 0.01}, vfx="mana", icon="FN"),
    # Assobio da Matinta
    S("support_ill_whistle", "Assobio Agourento",
      "Assobio num cone de 90° (4 células): inimigos com −20% de DEF por 8 s (−1,5% e +0,4 s por nível).",
      "support", MATINTA, 1, ROOT_T, {}, CONE, DEBUFF, 18, 14, radius=4, cone=90, dur=8,
      extra={"def_pct": -0.2, "def_pct_per_level": -0.015, "duration_per_level": 0.4}, vfx="debuff", icon="AA"),
    S("support_omen", "Agouro",
      "Um inimigo (10 células) fica com −25% de ATQ e −15% de MATQ por 10 s (+0,5 s por nível).",
      "support", MATINTA, 2, MATINTA, {"support_ill_whistle": 3}, SINGLE, DEBUFF, 16, 12, rng=10, dur=10,
      extra={"atk_pct": -0.25, "atk_pct_per_level": -0.015, "matk_pct": -0.15, "matk_pct_per_level": -0.01,
             "duration_per_level": 0.5}, vfx="debuff", icon="AG"),
    S("support_owl_cry", "Pio da Rasga-Mortalha",
      "Um pio numa área (3 células): lentidão de 40% por 5 s (+2% e +0,25 s por nível).",
      "support", MATINTA, 3, MATINTA, {"support_ill_whistle": 3}, GROUND_AREA, DEBUFF, 22, 16, rng=10, radius=3,
      dur=5, extra={"slow_pct": 0.4, "slow_pct_per_level": 0.02, "duration_per_level": 0.25},
      vfx="debuff", icon="PR"),
    S("support_bird_lime", "Visgo",
      "Cola o inimigo no chão (10 células): preso por 3 s (+0,15 s por nível).",
      "support", MATINTA, 4, MATINTA, {"support_omen": 3}, SINGLE, ROOT, 16, 14, rng=10, dur=3,
      extra={"duration_per_level": 0.15}, vfx="root", icon="VI"),
    S("support_bitter_smoke", "Fumaça Amarga",
      "Fumaça numa área (3 células) por 6 s: 30% do MATQ por segundo e −50% de cura recebida (+3% por nível).",
      "support", MATINTA, 5, MATINTA, {"support_owl_cry": 3}, GROUND_AREA, DOT, 24, 18, rng=10, radius=3,
      mult=0.3, per=0.03, dur=6, extra={"zone_heal_received_pct": -0.5}, vfx="poison", icon="FU"),
    # Casco de Jabuti (Velho Tião do Casco)
    S("tank_shell_knock", "Batida no Casco",
      "Bate no peito: os monstros a 4 células atacam você por 5 s (+0,25 s por nível).",
      "tank", JABUTI, 1, JABUTI, {}, SELF_AREA, TAUNT, 14, 12, radius=4, dur=5,
      extra={"duration_per_level": 0.25}, vfx="taunt", icon="BT"),
    S("tank_shell_retreat", "Recolher no Casco",
      "Recebe 50% menos dano e anda 50% mais devagar por 4 s (−2% e +0,2 s por nível).",
      "tank", JABUTI, 2, JABUTI, {"tank_shell_knock": 1}, SELF, BUFF, 16, 20, dur=4,
      extra={"dmg_taken_pct": -0.5, "dmg_taken_pct_per_level": -0.02, "self_slow_pct": 0.5,
             "duration_per_level": 0.2}, vfx="guard", icon="RC"),
    S("tank_hard_shell", "Casco Duro",
      "+30% de DEF por 12 s (+3% e +0,5 s por nível).",
      "tank", JABUTI, 3, JABUTI, {"tank_shell_knock": 3}, SELF, BUFF, 14, 25, dur=12,
      extra={"def_pct": 0.3, "def_pct_per_level": 0.03, "duration_per_level": 0.5}, vfx="guard", icon="CD"),
    S("tank_patience", "Paciência de Jabuti",
      "Recupera 3% da vida máxima por segundo por 8 s (+0,2% por nível).",
      "tank", JABUTI, 4, JABUTI, {"tank_shell_retreat": 3}, SELF, HOT, 18, 30, dur=8,
      extra={"hot_max_hp_pct": 0.03, "hot_max_hp_pct_per_level": 0.002}, vfx="heal", icon="PJ"),
    S("tank_shell_bash", "Empurrão de Casco",
      "Cone de 90° (2 células): 60% do ATQ, empurra 2 células e atordoa por 1 s (+6% e +0,05 s por nível).",
      "tank", JABUTI, 5, JABUTI, {"tank_hard_shell": 3}, CONE, KNOCKBACK, 16, 12, radius=2, cone=90, mult=0.6,
      per=0.06, extra={"knockback_cells": 2, "stun_sec": 1.0, "stun_per_level": 0.05}, vfx="knock", icon="EC"),
    # Couro de Anta
    S("tank_thick_hide", "Couro Grosso",
      "+40% de DEF por 15 s (+3% e +0,5 s por nível).",
      "tank", ANTA, 1, JABUTI, {}, SELF, BUFF, 16, 30, dur=15,
      extra={"def_pct": 0.4, "def_pct_per_level": 0.03, "duration_per_level": 0.5}, vfx="guard", icon="CU"),
    S("tank_tapir_stomp", "Pisada de Anta",
      "Pisa forte: 80% do ATQ em volta (2,5 células) e atordoa por 1,5 s (+6% e +0,05 s por nível).",
      "tank", ANTA, 2, ANTA, {"tank_thick_hide": 3}, SELF_AREA, STUN, 18, 14, radius=2.5, mult=0.8, per=0.06,
      dur=1.5, extra={"duration_per_level": 0.05}, vfx="stun", icon="PA"),
    S("tank_tapir_ram", "Trombada",
      "Avança até o alvo (6 células), causa 130% do ATQ e empurra 3 células (+10% por nível).",
      "tank", ANTA, 3, ANTA, {"tank_tapir_stomp": 1}, SINGLE, KNOCKBACK, 18, 14, rng=6, mult=1.3, per=0.1,
      extra={"dash": 1, "knockback_cells": 3}, vfx="knock", icon="TB"),
    S("tank_living_wall", "Muralha Viva",
      "Aliados a 3 células recebem 20% menos dano por 8 s (−1,5% e +0,4 s por nível).",
      "tank", ANTA, 4, ANTA, {"tank_thick_hide": 3}, SELF_AREA, BUFF, 24, 30, radius=3, dur=8,
      extra={"dmg_taken_pct": -0.2, "dmg_taken_pct_per_level": -0.015, "duration_per_level": 0.4},
      vfx="shield", icon="MV"),
    S("tank_stand_firm", "Aguentar Firme",
      "Imune a atordoar, prender e empurrar por 6 s (+0,3 s por nível).",
      "tank", ANTA, 5, ANTA, {"tank_living_wall": 3}, SELF, BUFF, 20, 40, dur=6,
      extra={"cc_immune": 1, "duration_per_level": 0.3}, vfx="guard", icon="AE"),
    # Fúria do Mapinguari
    S("tank_fury", "Fúria",
      "+40% de ATQ e −30% de DEF por 10 s (+3% ATQ e +0,5 s por nível).",
      "tank", MAPINGUARI, 1, JABUTI, {}, SELF, BUFF, 10, 30, dur=10,
      extra={"atk_pct": 0.4, "atk_pct_per_level": 0.03, "def_pct": -0.3, "duration_per_level": 0.5},
      vfx="buff", icon="FR"),
    S("tank_mapinguari_howl", "Urro do Mapinguari",
      "Urro em volta (4 células): inimigos com −25% de DEF por 8 s (−1,5% e +0,4 s por nível).",
      "tank", MAPINGUARI, 2, MAPINGUARI, {"tank_fury": 3}, SELF_AREA, DEBUFF, 16, 18, radius=4, dur=8,
      extra={"def_pct": -0.25, "def_pct_per_level": -0.015, "duration_per_level": 0.4}, vfx="debuff", icon="UM"),
    S("tank_heavy_claws", "Garras Pesadas",
      "Dois golpes num cone de 90° (2 células), 120% do ATQ cada (+10% por nível).",
      "tank", MAPINGUARI, 3, MAPINGUARI, {"tank_fury": 1}, CONE, MULTI_HIT, 18, 9, radius=2, cone=90, mult=1.2,
      per=0.1, extra={"hits": 2}, vfx="slash", icon="GP"),
    S("tank_battle_thirst", "Sede de Luta",
      "20% do dano causado volta como vida por 10 s (+1,5% e +0,5 s por nível).",
      "tank", MAPINGUARI, 4, MAPINGUARI, {"tank_heavy_claws": 3}, SELF, BUFF, 14, 30, dur=10,
      extra={"lifesteal": 0.2, "lifesteal_per_level": 0.015, "duration_per_level": 0.5}, vfx="buff", icon="SL"),
    S("tank_last_blow", "Última Pancada",
      "150% do ATQ, e até +150% conforme a vida que falta (+10% por nível).",
      "tank", MAPINGUARI, 5, MAPINGUARI, {"tank_mapinguari_howl": 3}, SINGLE, PHYSICAL, 20, 20, rng=1.5,
      mult=1.5, per=0.1, extra={"missing_hp_bonus": 1.5}, vfx="slash", icon="UP"),
]

# ------------------------------------------------------------------ quests de lição
# Monstro e item de cada escola (monstros do Sabiá que existem em data/monsters).
SCHOOL_PREY = {
    "blade": ("prank_whirlwind", "spinning_leaf"),
    "arcane": ("enchanted_firefly", "firefly_light"),
    "bow": ("prank_whirlwind", "spinning_leaf"),
    "hybrid": ("enchanted_firefly", "firefly_light"),
    "support": ("enchanted_firefly", "firefly_light"),
    "tank": ("stone_armadillo", "armadillo_shell"),
}
PREY_PLURAL = {"prank_whirlwind": "Redemoinhos Arteiros", "enchanted_firefly": "Vaga-lumes Encantados",
               "stone_armadillo": "Tatus-Pedra"}
ITEM_PLURAL = {"spinning_leaf": "Folhas Rodopiantes", "firefly_light": "Luzes de Vaga-lume",
               "armadillo_shell": "Cascos de Tatu-Pedra"}

MASTER_NAMES = {
    "master_brisa": "Mestra Brisa", "master_orvalho": "Mestre Orvalho", "master_taquari": "Mestre Taquari",
    "elder_ze_ferreiro": "Seu Zé Ferreiro", "elder_aninha": "Vó Aninha", "elder_tiao": "Velho Tião",
}
# Falas por mestre: oferta ({skill}, {n}, {mon}, {collect}), andamento e conclusão ({skill}).
MASTER_VOICE = {
    "master_brisa": (
        "Quer aprender {skill}? Primeiro, mostre que está pronto. Derrote {n} {mon}{collect}. Depois volte aqui.",
        "Ainda falta um pouco. Termine o que eu pedi e volte.",
        "Muito bem. Agora você sabe usar {skill}. Treine bastante."),
    "master_orvalho": (
        "Para aprender {skill}, preciso ver você lutar com calma. Derrote {n} {mon}{collect}. Depois venha falar comigo.",
        "Ainda não terminou. Volte quando fizer tudo.",
        "Pronto! Agora {skill} é sua. Use com cuidado."),
    "master_taquari": (
        "Quer aprender {skill}? Derrote {n} {mon}{collect}. Ataque de longe e não deixe chegarem perto.",
        "Ainda falta. Termine a caçada e volte.",
        "Isso! Agora você sabe usar {skill}. Mire com calma e solte."),
    "elder_ze_ferreiro": (
        "Para aprender {skill}, preciso ver sua força. Derrote {n} {mon}{collect}. Depois volte à forja.",
        "Ainda não terminou. Volte quando fizer tudo.",
        "Muito bem. Agora {skill} é sua. Cuide bem dela."),
    "elder_aninha": (
        "Quer aprender {skill}, meu bem? Derrote {n} {mon}{collect}. Depois volte para a Vó.",
        "Ainda falta um pouco, meu bem. Termine e volte.",
        "Pronto. Agora você sabe usar {skill}. Use para cuidar dos seus amigos."),
    "elder_tiao": (
        "Quer aprender {skill}? Aguente a luta contra {n} {mon}{collect}. Depois volte aqui.",
        "Calma, ainda falta. Termine e volte.",
        "Muito bem. Agora {skill} é sua. Quem aguenta firme fica forte."),
}

# ------------------------------------------------------------------ quests dos anciãos (§3.3)
ELDER_QUESTS = [
    dict(id="elder_ze_steel_song", giver="elder_ze_ferreiro", name="Aço que Canta",
         desc="Seu Zé Ferreiro vai fazer um facão de brasa para você. Traga brasas eternas, derrote dois chefes e vença o fantoche.",
         titles=["sabia_blade_machete", "sabia_arcane_firefly"], reward_title="sabia_hybrid_ember",
         reward_skill="hybrid_spark_blade", xp=800,
         steps=[dict(type="COLLECT", target="eternal_ember", count=2, text="Colete Brasas Eternas (de Vaga-lume Encantado raro ou chefe)"),
                dict(type="KILL", target="enchanted_firefly", count=1, variant="boss", text="Derrote o chefe Rainha-Lume do Brejo"),
                dict(type="KILL", target="", count=1, variant="atroz", text="Derrote um chefe em forma atroz (à noite)"),
                dict(type="TRIAL", target="trial_twin_shield_puppet", count=1, time=90.0,
                     text="Provação: derrube o fantoche de dois escudos do Seu Zé")],
         option="[Missão] Quero um facão de brasa.",
         offer="Você já sabe as duas coisas. Então vamos fazer o seu facão. Primeiro, me traga duas Brasas Eternas. Depois, derrote a Rainha-Lume do Brejo. Depois, derrote um chefe na forma atroz, à noite. Por último, derrube o meu fantoche de dois escudos.",
         progress="Ainda falta. Volte quando fizer tudo.",
         complete="Pronto, o facão está feito. Agora você é Brasa no Facão. E aprendeu a Lâmina Faiscante."),
    dict(id="elder_aninha_root_fire", giver="elder_aninha", name="A Raiz Debaixo do Fogo",
         desc="Vó Aninha quer ver se você cuida bem de todos. Traga raízes de pequi, derrote dois chefes e proteja as 3 mudas até o fim.",
         titles=["sabia_arcane_firefly", "sabia_arcane_crystal", "sabia_bow_cerrado"], reward_title="sabia_support_root",
         reward_skill="support_bottle_brew", xp=800,
         steps=[dict(type="COLLECT", target="pequi_root", count=3, text="Colete Raízes de Pequi (de Redemoinho Arteiro raro ou chefe)"),
                dict(type="KILL", target="", count=1, variant="boss", no_death=True,
                     text="Derrote um chefe sem cair (sozinho vale)"),
                dict(type="KILL", target="", count=1, variant="atroz", text="Derrote um chefe em forma atroz (à noite)"),
                dict(type="TRIAL", target="prank_whirlwind", count=1, time=60.0, mode="protect", spawn=3, wave=20.0,
                     protect="pequi_seedling", protect_count=3, protect_min=1,
                     text="Provação: proteja as 3 mudas até o fim (60 s)")],
         option="[Missão] Quero aprender com a senhora, Vó.",
         offer="Você já sabe as três coisas, meu bem. Então vou te ensinar. Primeiro, me traga três Raízes de Pequi. Depois, derrote um chefe sem cair. Depois, derrote um chefe na forma atroz, à noite. Por último, vou plantar 3 mudas de pequizeiro. Os redemoinhos vão atacar as mudas. Proteja as 3 mudas até o fim: cure, faça escudo, lute. Basta uma ficar de pé.",
         progress="Ainda falta um pouco, meu bem. Termine e volte.",
         complete="As mudas ficaram de pé, e você cuidou delas como a raiz cuida do cerrado. Agora você é Raiz do Cerrado. E aprendeu a Garrafada."),
    dict(id="elder_tiao_sky_feast", giver="elder_tiao", name="O Casco da Festa no Céu",
         desc="Velho Tião quer ver você cair e levantar. Traga cacos de casco, derrote três chefes e aguente seis tatus ao mesmo tempo.",
         titles=["sabia_blade_machete", "sabia_blade_aroeira", "sabia_blade_jaguar"], reward_title="sabia_tank_jabuti",
         reward_skill="tank_shell_knock", xp=800,
         steps=[dict(type="COLLECT", target="ancient_shell_shard", count=3, text="Colete Cacos de Casco Antigo (de Tatu-Pedra raro ou chefe)"),
                dict(type="KILL", target="", count=2, variant="boss", distinct=True,
                     text="Derrote 2 chefes de espécies diferentes"),
                dict(type="KILL", target="stone_armadillo", count=1, variant="atroz",
                     text="Derrote o Tatu-Pedra chefe em forma atroz (à noite)"),
                dict(type="TRIAL", target="stone_armadillo", count=1, time=45.0, mode="survive", spawn=6, wave=0.0,
                     text="Provação: aguente seis tatus por 45 s sem cair")],
         option="[Missão] Quero um casco duro como o do jabuti.",
         offer="Você já provou as três coisas. Então vou te ensinar. Primeiro, me traga três Cacos de Casco Antigo. Depois, derrote dois chefes de bichos diferentes. Depois, derrote o Tatu-Pedra chefe na forma atroz, à noite. Por último, aguente seis tatus em cima de você por 45 segundos.",
         progress="Calma, ainda falta. Termine e volte.",
         complete="Você caiu e levantou, como o jabuti. Agora você é Casco de Jabuti. E aprendeu a Batida no Casco."),
]

# ------------------------------------------------------------------ NPCs novos e diálogos
# Opção: (texto, próximo nó) ou (texto, próximo nó, {"cond": {...}, "action": ..., "args": {...}}).
# Próximo nó vazio e sem ação = fecha. As opções de quest entram sozinhas no nó "start" (QuestService).
def _elder_nodes(quest_id, parts, need, back):
    return {
        "legend_1": (parts[0], [("E depois?", "legend_2")]),
        "legend_2": (parts[1], [("E o que é preciso?", "need")]),
        "need": (need, [
            ("Eu já sei essas coisas.", "", {"cond": {"quest_available": quest_id}, "action": "quest_offer",
                                             "args": {"quest_id": quest_id}}),
            ("Ainda não sei.", "come_back", {"cond": {"quest_locked": quest_id}}),
            ("Obrigado pela história.", "", {"cond": {"quest_taken": quest_id}}),
        ]),
        "come_back": (back, [("Vou aprender e volto.", "")]),
    }


NPCS = {
    "master_taquari": dict(name="Mestre Taquari", fallback="res://assets/npcs/npc_master_brisa", speed=1.6,
        start="Olá. Eu sou Taquari. Caço no cerrado desde menino. Eu ensino a usar o arco.",
        opts=[("Como eu começo no arco?", "about"), ("Tem alguma dica?", "tip"), ("Até mais, mestre.", "")],
        nodes={
            "about": ("Primeiro, compre um arco na loja do porto. Depois, aprenda comigo três técnicas: Tiro Rasante, Flecha Dupla e Arco Tenso. Quem aprende as três vira Flecha do Cerrado.",
                      [("Tem alguma dica?", "tip"), ("Vou comprar um arco.", "")]),
            "tip": ("Não deixe o bicho chegar perto. Atire, recue e atire de novo. O arco usa a sua Destreza.",
                    [("Obrigado, mestre.", "")]),
        }),
    "elder_ze_ferreiro": dict(name="Seu Zé Ferreiro", fallback="res://assets/npcs/npc_boatman", speed=1.2,
        start="Olá! Eu sou o Zé, o ferreiro do porto. Faço facões há muitos anos.",
        opts=[("Conte uma história, seu Zé.", "legend_1"), ("Até mais, seu Zé.", "")],
        nodes=_elder_nodes("elder_ze_steel_song",
            ["Quando eu era menino, a forja apagou no meio de um serviço. Sem fogo não tinha facão. Aí entrou pela janela um enxame de vaga-lumes e pousou no carvão.",
             "O carvão acendeu de novo, com uma luz que eu nunca tinha visto. O facão que saiu daquela brasa cortava e soltava faísca ao mesmo tempo."],
            "Só consegue usar um facão desses quem aprendeu as duas coisas: segurar a lâmina com firmeza e acender a luz dos vaga-lumes.",
            "Volte quando tiver aprendido essas duas coisas.")),
    "elder_aninha": dict(name="Vó Aninha, a raizeira", fallback="res://assets/npcs/npc_fruit_vendor", speed=1.0,
        start="Olá, meu bem. Eu sou a Vó Aninha, raizeira. Conheço as plantas que curam.",
        opts=[("Conte uma história, Vó.", "legend_1"), ("Até logo, Vó.", "")],
        nodes=_elder_nodes("elder_aninha_root_fire",
            ["Todo ano o fogo passa pelo cerrado e deixa tudo preto. Quem olha acha que nada vai voltar. Mas, debaixo da terra, as raízes guardaram água.",
             "Na primeira chuva, tudo brota de novo. Eu aprendi a cuidar das pessoas do jeito que essas raízes cuidam do cerrado."],
            "Para aprender comigo, você precisa saber três coisas: acender uma luz no escuro, proteger os amigos com um escudo de cristal e acertar de longe com o arco.",
            "Volte quando tiver aprendido essas três coisas.")),
    "elder_tiao": dict(name="Velho Tião do Casco", fallback="res://assets/npcs/npc_fisherman", speed=0.9,
        start="Olá. Eu sou o Tião, o do Casco. Já apanhei muito nesta vida e sempre levantei.",
        opts=[("Conte uma história, seu Tião.", "legend_1"), ("Até mais, seu Tião.", "")],
        nodes=_elder_nodes("elder_tiao_sky_feast",
            ["Conhece a história da festa no céu? Todos os bichos foram convidados, mas o jabuti não sabia voar. Ele se escondeu dentro da viola do urubu e subiu junto.",
             "Na volta, o urubu descobriu e jogou o jabuti lá de cima. O casco quebrou em mil pedaços. Os amigos juntaram pedaço por pedaço, e o casco ficou todo marcado, mas mais duro do que antes."],
            "Até hoje é assim: quem cai e levanta fica forte como o jabuti. Eu só ensino quem já provou três coisas: segurar o facão sem tremer, aguentar golpes como a aroeira e atacar certeiro como a onça.",
            "Volte quando tiver aprendido essas três coisas.")),
}

# ------------------------------------------------------------------ textos fixos (mensagens e janela de skills)
STATIC_LOC = {
    "progression": {
        "PROG_MSG_NEEDS_BOW": "Essa técnica precisa de um arco equipado.",
        "PROG_MSG_BLINK_BLOCKED": "Não dá para aparecer ali: escolha uma célula livre.",
        "PROG_REQ_SKILL_KNOWN": "— você já conhece %s",
        "PROG_MSG_TRIAL_SURVIVED": "%s: você aguentou firme até o fim!",
        "PROG_DEV_REPLY": "[dev] %s",
        "PROG_MSG_PROTECTED_HP": "%s: %d/%d de vida.",
        "PROG_MSG_TRIAL_PROTECTED": "Muito bem! %d muda(s) ficaram de pé até o fim.",
        "PROG_MSG_TRIAL_PROTECT_FELL": "Uma muda caiu! Restam %d.",
        "PROG_MSG_TRIAL_PROTECT_LOST": "%s: as três mudas caíram. Fale com a Vó Aninha para tentar de novo.",
        "UI_SKILL_REQ_LEVEL": "%s no nível %d",
        "UI_SKILL_REQ_TITLE": "título %s",
        "UI_SKILL_REQ_OK": "%s (ok)",
        "UI_SKILL_REQ_NO": "%s (falta)",
        "UI_SKILL_MISSING": "Falta: %s",
        "UI_SKILL_LEARN_WITH": "Lição com %s",
        "UI_SKILL_TREE_OF": "Árvore: %s",
        "UI_SKILL_TREE_MASTER": "quem ensina: %s",
        "UI_SKILL_TREE_LOCKED": "título ainda não conquistado",
        "UI_SKILL_TREE_INHERITS": "ramo de %s",
        "UI_SKILL_TREE_OTHER": "Outras",
        "UI_SKILL_NEEDS_BOW": "Precisa de arco equipado",
    },
    "content": {
        "ITEM_SIMPLE_BOW_NAME": "Arco Simples",
        "ITEM_SIMPLE_BOW_DESC": "Arco de madeira de ipê com corda de tucum. Duas mãos; o dano vem da Destreza. Alcance de 8 células.",
    },
}
